require('mehdi/packer')
require('mehdi/settings')
require('mehdi/mappings')
require('mehdi/lsp.servers')
require('mehdi/telescope-config')
require('mehdi/cmp')
require('mehdi/comment')
require('mehdi/dap')
require('mehdi/treesitter')
require('mehdi/colorschemes')
require('mehdi/lualine')
require('mehdi/toggleterm')
require('mehdi/treesitter-context')
require('mehdi/harpoon')
require('mehdi/gitsigns')
-- require('mehdi/diffview')
